# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['eduplay_studio/app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('eduplay_studio/eduplay/resources', 'eduplay/resources'),
        ('eduplay_studio/assets_bundle', 'assets_bundle'),
    ],
    hiddenimports=[
        'PySide6',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtMultimedia',
        'PySide6.QtPrintSupport',
        'pygame',
        'docx',
        'fitz',
        'openpyxl',
        'sqlalchemy',
        'requests',
        'jinja2',
        'PIL',
        'firebase_admin',
        'pywebview',
        'win32com.client',
        'eduplay',
        'eduplay.ui',
        'eduplay.core',
        'eduplay.ui.screens',
        'eduplay.ui.widgets',
        'eduplay.core.i18n',
        'eduplay.core.project_manager',
        'eduplay.core.ai_service',
        'eduplay.core.export_service',
        'eduplay.core.import_service',
        'eduplay.core.asset_manager',
        'eduplay.core.settings_manager',
        'eduplay.core.ppt_vsto_addin_service',
        'eduplay.core.preview_runner',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='EduPlayStudio',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    icon=['eduplay_studio\\eduplay\\resources\\icons\\icon.ico'],
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='EduPlayStudio',
)
