//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace EduPlay.PowerPointAddin
{
    /// <summary>
    /// Designer support for PowerPoint add-in.
    /// </summary>
    [global::Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name = "FullTrust")]
    [System.Diagnostics.DebuggerNonUserCode()]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.AddInBase
    {
        internal Microsoft.Office.Interop.PowerPoint.Application Application;

        [System.Diagnostics.DebuggerNonUserCode()]
        public ThisAddIn(Microsoft.Office.Tools.Factory factory, System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        /// <summary>
        /// Initializes the add-in. This method is required for Designer support and should not be modified.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        protected override void Initialize()
        {
            base.Initialize();
            try
            {
                this.Application = this.GetHostItem<Microsoft.Office.Interop.PowerPoint.Application>(typeof(Microsoft.Office.Interop.PowerPoint.Application), "Application");
            }
            catch (System.Exception ex)
            {
                LogException("Initialize failed: GetHostItem(Application)", ex);
            }

            try
            {
                Globals.ThisAddIn = this;
            }
            catch (System.Exception ex)
            {
                LogException("Initialize failed: Globals.ThisAddIn", ex);
            }
        }

        /// <summary>
        /// Finalizes the add-in. This method is required for Designer support and should not be modified.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        protected override void FinishInitialization()
        {
            this.InternalStartup();
            this.OnStartup();
        }
    }

    internal sealed partial class Globals
    {
        internal static Microsoft.Office.Tools.Factory Factory;
        private static ThisAddIn _ThisAddIn;

        internal static ThisAddIn ThisAddIn
        {
            get { return _ThisAddIn; }
            set
            {
                _ThisAddIn = value;
            }
        }
    }
}
#pragma warning restore 414
